version: '3.8'

services:

  nginx:

    build: 

      context: .

    ports:

      - "80:80"

    depends_on:
      - api

    volumes:
      - type: volume
        source: nginxLog
        target : /var/log/nginx

      - type: bind

        source: ./nginx/deployment/default.conf 

        target: /etc/nginx/conf.d/default.conf


  api:
    build: 
      context: ./api

    env_file:
      - .env
    # set up all the required environament  variables required by the api service
    environment:
      # Api Required Keys Configs
      SECRET_KEY: "${SECRET_KEY}"
      ACTIVATION_KEY: "${ACTIVATION_KEY}"
      ACCESS_KEY: "${ACCESS_KEY}"
      REFRESH_KEY: "${REFRESH_KEY}"
      # Database configs
      MARIADB_USER: "${DATABASE_USER}"
      MARIADB_PASSWORD: "${DATABASE_PASSWORD}"
      MARIADB_DATABASE: "${DATABASE_NAME}"
      # Mail server Configs
      MAIL_PORT: "${MAIL_PORT}"
      MAIL_SENDER: "${MAIL_SENDER}"
      MAIL_SERVER: "${MAIL_SERVER}"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      # Redis server Configs
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: 6379
      REDIS_PASSWORD: "${REDIS_PASSWORD}"

      FLASK_ENV: "production"

    depends_on:
      # - database
      database:
        condition: service_healthy

    volumes:

      - type : bind
        source: ./api
        target: /api
    # use gunicon to serve the  appication

    # command: gunicorn --bind 0.0.0.0:5000 manage:app
    command: ./deploy.sh

  database:

    build:

      context: ./api/database

    environment:  
    #  Setting up environament variables 
      MARIADB_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_NAME}"
    

    healthcheck:
      test: ["CMD","/usr/local/bin/healthcheck.sh", "--su=mysql", "--connect", "--innodb_initialized"]
      
    restart : always
    
  
    expose:

      - 3160

    volumes:

      - type : volume
        source : mysqlData
        target: /var/lib/mysql  

  redis:

    image: 'bitnami/redis:latest'

    restart: always

    environment:

      - REDIS_PASSWORD="${REDIS_PASSWORD}"
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG

    expose:
      - 6379

    volumes:

      - type : volume
        source: redisData
        target : /data

    
volumes:

  mysqlData:

    driver: local

  redisData:

    driver: local

  nginxLog:

    driver: local
