name: Application Component unit testing

on:
  push:
    branches:
      - development

      - Interface

  pull_request:

    branches:

      - development

jobs:

  Component-Unit_Testing:

    runs-on: ubunut-latest

    strategy:

      matrix:

        node_version: [14.X, 15.X]

    steps:

      - name: Checking out the repository

        uses: actions/checkout@v2

      - name: Using node version ${{matrix.node_verison}}

        uses: actions/setup-node@v2

        with:

          node_version: ${{matrix.node_version}}

      - name: npm ci, build and test

        run: |

            npm ci

            npm run build --if-present

            npm test