name: Application E2E Testing

on:

  push:

    branches:

      - deployment

      - Interface

  pull_request:

    branches:

      - deployment


jobs:

  E2E-Testing:

    runs-on: ubuntu-latest

    steps:

      - name: Checking out the repository
        uses: actions/checkout@v2

      - name: Running cypress E2E tests

        uses: cypress-io/github-action@v2

        with:

          start : npm start




